### ISSUE TITLE
Card is not displayed when first rendered until "ion toggle icon on" switch is turned off (or any states change)

### ISSUE THREAD

**Issue by 35gh** [sicknesz/midea-inventor-card#6] opened 2022-01-31 20:01 UTC
Impacted versions: 1.07 and v1.06

When installing the card for the first time, the editor does not display it:
![Capture d’écran 2022-01-31 à 20 55 29](https://user-images.githubusercontent.com/90415090/151863873-a1898cb1-adcb-48af-9c9e-33b8c9021134.png)

But when I toggle the "ion toggle icon on" switch off and on again, then it start to work, the card appears and persists toggle change:

![Capture d’écran 2022-01-31 à 20 55 38](https://user-images.githubusercontent.com/90415090/151864006-ed0b5738-f6f4-4e01-b0f8-ef40ace50b4b.png)

**Comment by sicknesz** [comment] 2022-01-31 20:09
Yeah, i've never been able to track this one down, i'll try to give it another try tomorrow, it should render even freshly installed, it can also happen when you restart but as you mentionned clicking on anything fix the issue, any change in the state will trigger the render and from there it will work just fine. 
Next episode : tomorrow ! :)

PS: Thanks alot for the repo star man !

**Comment by 35gh** [comment] 2022-01-31 20:11
Thanks! 

Side bug: my humidifier does not have the ionizer feature, but the ion entity is indicated as mandatory ("requis") in the editor.

**Comment by sicknesz** [comment] 2022-01-31 20:11
Just noticed the "Required" mention to the ion entity which is false, it's NOT mandatory at all, fixed in the next release, thanks for you inputs and helping me make this a better card ! :)

**Comment by sicknesz** [comment] 2022-01-31 20:14
I have a good news about hacs :

![Screenshot_20220131_211331](https://user-images.githubusercontent.com/3835626/151865816-a9c2d1c6-51dd-4b4a-92a5-012b4221e13d.png)
 
 Updates are working ;)

**Comment by Bimboboy007** [comment] 2022-01-31 21:04
With the MDDF 20DE7-WF and the Inventor EVA ION PRO WiFi, the card works as far as I can tell.

**Comment by sicknesz** [comment] 2022-02-01 18:28
@Bimboboy007 : it's a random glitch more than a bug, on the first time you add the card to lovelace it can sometimes render nothing until you click anything, it's not really an issue, but id be glad to get rid of it that's why i let this issue open until i take a deeper look, Thanks for using the card :)

**Comment by sicknesz** [comment] 2022-04-30 18:28
closing since no updates in the last months

**Closed as completed by sicknesz** 2022-04-30 18:28 UTC
Labels: bug

**Comment by brettgoss** [comment] 2022-05-05 06:55
Just added this card (thank you for making it, by the way!), and ran into this bug. I can actually reliably reproduce it - enabling `Toggle ion toggle icon off` causes the card to vanish, and disabling that toggle shows it again. 

**Toggle off**
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1578328/166875150-00bcddb3-65ac-4326-a4ea-80c775b635a6.png">

**Toggle on**
<img width="797" alt="image" src="https://user-images.githubusercontent.com/1578328/166875201-b797561c-2fd2-4437-b52e-555790c56d2b.png">

Let me know if you would like more information or help tracking this down!

**Comment by brettgoss** [comment] 2022-05-05 07:05
Oh, actually, I have a JS console error when it's not rendering in the editor:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1578328/166876053-a76c1a91-2a91-4f83-841d-7afd25242c63.png">

Which is failing here in the minified code:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1578328/166876184-58db3d1a-79b3-4aa1-85f5-3295a6d7c34f.png">

and that points to this line, by the looks of it:
https://github.com/sicknesz/midea-humidifier-card/blob/master/src/midea-humidifier-card.ts#L687

I'm not familiar enough with the development process here to actually try to find a fix, but let me know if I can help in any way!
